### PR TITLE
Use latest flow

### PR DESCRIPTION
**Pull request by alvarezguille**
This change is [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-components-testbench/33)

### CODE REVIEW

**Comment by alvarezguille** [comment]
Removed webjars-bom, still needs new component versions compatible with beta8 including the change `HasClickListeners` -> `ClickNotifier`

**Comment by alvarezguille** [comment]
*[vaadin-components-testbench-test/pom.xml, line 27 at r7](https://reviewable.io/reviews/vaadin/vaadin-components-testbench/33#-LB_fanBBNHu1GRdjMwh:-LB_fanC5ku7kB3TKEt4:b56eono) ([raw file](https://github.com/vaadin/vaadin-components-testbench/blob/630746357134e84a8bc3496180a65c9a1d00768a/vaadin-components-testbench-test/pom.xml#L27)):*
> ```XML
>         <vaadin.button.flow.version>1.0.0.beta7</vaadin.button.flow.version>
>         <vaadin.checkbox.flow.version>1.0.0.beta6</vaadin.checkbox.flow.version>
>         <vaadin.combo.box.flow.version>1.0.0.beta8</vaadin.combo.box.flow.version>
> ```

should be beta9

---


*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-components-testbench/33)*

**Comment by oluwasayo** [comment]
Review status: 0 of 10 files reviewed at latest revision, all discussions resolved.

---

*[vaadin-components-testbench-test/pom.xml, line 27 at r7](https://reviewable.io/reviews/vaadin/vaadin-components-testbench/33#-LB_fanBBNHu1GRdjMwh:-LB_qzam0Rb-5NkFqrip:bb6un1j) ([raw file](https://github.com/vaadin/vaadin-components-testbench/blob/630746357134e84a8bc3496180a65c9a1d00768a/vaadin-components-testbench-test/pom.xml#L27)):*
<details><summary><i>Previously, alvarezguille (Guille) wrote…</i></summary><blockquote>

should be beta9
</blockquote></details>

Done

---


*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-components-testbench/33)*

**Comment by alvarezguille** [comment]
Reviewed 6 of 8 files at r5, 2 of 3 files at r7, 1 of 1 files at r8.
Review status: 9 of 10 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-components-testbench/33)*

**Comment by alvarezguille** [comment]
Reviewed 1 of 3 files at r7.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-components-testbench/33)*

**Pull request merged**
